import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_PATH = ROOT / '.env'

SECRET_FIELDS = {
    'webhook': 'DINGTALK_WEBHOOK',
    'secret': 'DINGTALK_SECRET',
}
ROBOT_KEY_PREFIX = 'DINGTALK_ROBOT_'


def _parse_env_value(value: str) -> str:
    text = value.strip()
    if len(text) >= 2 and text[0] == text[-1] and text[0] in ('"', "'"):
        return text[1:-1]
    return text


def load_env_file(env_path: Path = ENV_PATH):
    data = {}
    if not env_path.exists():
        return data
    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        data[key.strip()] = _parse_env_value(value)
    return data


def save_env_file(values, env_path: Path = ENV_PATH):
    env_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        '# Generated by WebUI. Do not commit real secrets.',
    ]
    for key in sorted(values.keys()):
        value = str(values.get(key, '') or '')
        encoded = json.dumps(value, ensure_ascii=False)
        lines.append(f'{key}={encoded}')
    env_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def _sanitize_env_name(text: str) -> str:
    base = re.sub(r'[^A-Za-z0-9]+', '_', str(text or '').strip()).strip('_').upper()
    return base or 'DEFAULT'


def build_robot_env_keys(robot_id: str):
    suffix = _sanitize_env_name(robot_id)
    return {
        'webhook': f'{ROBOT_KEY_PREFIX}{suffix}_WEBHOOK',
        'secret': f'{ROBOT_KEY_PREFIX}{suffix}_SECRET',
    }


def load_dingtalk_secrets(env_path: Path = ENV_PATH):
    env = load_env_file(env_path)
    return {
        field: env.get(env_key, '')
        for field, env_key in SECRET_FIELDS.items()
    }


def save_dingtalk_secrets(webhook=None, secret=None, env_path: Path = ENV_PATH):
    env = load_env_file(env_path)
    updates = {
        'webhook': webhook,
        'secret': secret,
    }
    for field, value in updates.items():
        if value is None:
            continue
        env[SECRET_FIELDS[field]] = str(value).strip()
    save_env_file(env, env_path)


def load_robot_secrets(robot_id: str, env_path: Path = ENV_PATH):
    env = load_env_file(env_path)
    keys = build_robot_env_keys(robot_id)
    return {
        'webhook': env.get(keys['webhook'], ''),
        'secret': env.get(keys['secret'], ''),
        'env_keys': keys,
    }


def save_robot_secrets(robot_id: str, webhook=None, secret=None, env_path: Path = ENV_PATH):
    env = load_env_file(env_path)
    keys = build_robot_env_keys(robot_id)
    if webhook is not None:
        env[keys['webhook']] = str(webhook).strip()
    if secret is not None:
        env[keys['secret']] = str(secret).strip()
    save_env_file(env, env_path)
    return keys


def delete_robot_secrets(robot_id: str, env_path: Path = ENV_PATH):
    env = load_env_file(env_path)
    keys = build_robot_env_keys(robot_id)
    env.pop(keys['webhook'], None)
    env.pop(keys['secret'], None)
    save_env_file(env, env_path)


def mask_secret(value: str, head: int = 6, tail: int = 4):
    text = str(value or '').strip()
    if not text:
        return ''
    if len(text) <= head + tail:
        return '*' * len(text)
    return f'{text[:head]}***{text[-tail:]}'


def build_dingtalk_secret_status(secrets):
    webhook = str((secrets or {}).get('webhook') or '').strip()
    secret = str((secrets or {}).get('secret') or '').strip()
    return {
        'webhook': {
            'configured': bool(webhook),
            'masked': mask_secret(webhook, head=18, tail=8),
        },
        'secret': {
            'configured': bool(secret),
            'masked': mask_secret(secret, head=6, tail=6),
        },
    }


def build_robot_secret_status(robot_id: str, env_path: Path = ENV_PATH):
    data = load_robot_secrets(robot_id, env_path=env_path)
    status = build_dingtalk_secret_status(data)
    status['env_keys'] = data.get('env_keys', {})
    return status


def migrate_config_secrets(config_path: Path, env_path: Path = ENV_PATH):
    config_path = Path(config_path)
    if not config_path.exists():
        return {'migrated': False, 'reason': 'config_missing'}
    cfg = json.loads(config_path.read_text(encoding='utf-8'))
    defaults = cfg.get('defaults', {}) or {}
    dingtalk = defaults.get('dingtalk', {}) or {}
    webhook = str(dingtalk.get('webhook') or '').strip()
    secret = str(dingtalk.get('secret') or '').strip()
    webhook_real = webhook and 'YOUR_ACCESS_TOKEN' not in webhook and '***' not in webhook
    secret_real = secret and 'YOUR_SECRET' not in secret and '***' not in secret
    if not webhook_real and not secret_real:
        return {'migrated': False, 'reason': 'no_real_secrets_in_config'}

    current = load_dingtalk_secrets(env_path)
    save_dingtalk_secrets(
        webhook=webhook if webhook_real and not current.get('webhook') else None,
        secret=secret if secret_real and not current.get('secret') else None,
        env_path=env_path,
    )

    defaults.setdefault('dingtalk', {})
    defaults['dingtalk']['webhook'] = ''
    defaults['dingtalk']['secret'] = ''
    cfg['defaults'] = defaults
    config_path.write_text(json.dumps(cfg, ensure_ascii=False, indent=2), encoding='utf-8')
    return {'migrated': True}
